#############################################################################
# Makefile for building: cube.app/Contents/MacOS/cube
# Generated by qmake (3.0) (Qt 5.5.1)
# Project:  ParticleSystem.pro
# Template: app
# Command: /Users/Alice/Qt/5.5/clang_64/bin/qmake -spec macx-clang CONFIG+=debug CONFIG+=x86_64 -o Makefile ParticleSystem.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.7 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -std=c++11 -stdlib=libc++ -mmacosx-version-min=10.7 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I. -I/usr/include -Ipackages/obj-0.1 -I/usr/local/include -I/usr/local/include/SDL2 -I/Library/Frameworks/SDL2_image.framework/Headers -I/Users/Alice/Desktop/P/PPP2Ass/PSFinal/include -IGLFunctionsLib/include -I../../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers -I../../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/AGL.framework/Headers -I../../../../Qt/5.5/clang_64/mkspecs/macx-clang -F/Users/Alice/Qt/5.5/clang_64/lib
QMAKE         = /Users/Alice/Qt/5.5/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = cube1.0.0
DISTDIR = /Users/Alice/Desktop/P/PPP2Ass/PSFinal/obj/cube1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -stdlib=libc++ -mmacosx-version-min=10.7 -Wl,-rpath,/Users/Alice/Qt/5.5/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/Alice/Qt/5.5/clang_64/lib -F/Library/Frameworks -framework SDL2 -framework SDL2_image -L /Users/Alice/Desktop/P/PPP2Ass/PSFinal/GLFunctionsLib/lib -lGLFunctionsLib -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = 

####### Output directory

OBJECTS_DIR   = obj/

####### Files

SOURCES       = src/main.cpp \
		src/scene.cpp \
		src/particle.cpp \
		GLFunctionsLib/src/GLFunctions.cpp \
		GLFunctionsLib/src/Mat4.cpp \
		GLFunctionsLib/src/Vec4.cpp \
		src/particlesystem.cpp 
OBJECTS       = obj/main.o \
		obj/scene.o \
		obj/particle.o \
		obj/GLFunctions.o \
		obj/Mat4.o \
		obj/Vec4.o \
		obj/particlesystem.o
DIST          = README.md \
		../../../../Qt/5.5/clang_64/mkspecs/features/spec_pre.prf \
		../../../../Qt/5.5/clang_64/mkspecs/qdevice.pri \
		../../../../Qt/5.5/clang_64/mkspecs/features/device_config.prf \
		../../../../Qt/5.5/clang_64/mkspecs/common/unix.conf \
		../../../../Qt/5.5/clang_64/mkspecs/common/mac.conf \
		../../../../Qt/5.5/clang_64/mkspecs/common/macx.conf \
		../../../../Qt/5.5/clang_64/mkspecs/common/sanitize.conf \
		../../../../Qt/5.5/clang_64/mkspecs/common/gcc-base.conf \
		../../../../Qt/5.5/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../../Qt/5.5/clang_64/mkspecs/common/clang.conf \
		../../../../Qt/5.5/clang_64/mkspecs/common/clang-mac.conf \
		../../../../Qt/5.5/clang_64/mkspecs/qconfig.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcollision.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcollision_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquickrenderer.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquickrenderer_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3drenderer.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3drenderer_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_enginio.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/features/qt_functions.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/qt_config.prf \
		../../../../Qt/5.5/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../../Qt/5.5/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../../Qt/5.5/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/default_pre.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/resolve_config.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/default_post.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/c++11.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/mac/sdk.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/mac/default_post.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/warn_on.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/qt.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/resources.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/moc.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/unix/opengl.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/unix/thread.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/mac/rez.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/testcase_targets.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/exceptions.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/yacc.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/lex.prf \
		ParticleSystem.pro src/scene.h \
		src/particle.h \
		GLFunctionsLib/include/GLFunctions.h \
		GLFunctionsLib/include/Mat4.h \
		GLFunctionsLib/include/Vec4.h \
		src/particlesystem.h src/main.cpp \
		src/scene.cpp \
		src/particle.cpp \
		GLFunctionsLib/src/GLFunctions.cpp \
		GLFunctionsLib/src/Mat4.cpp \
		GLFunctionsLib/src/Vec4.cpp \
		src/particlesystem.cpp
QMAKE_TARGET  = cube
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = cube.app/Contents/MacOS/cube

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-g \
		-isysroot \
		/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk \
		-std=c++11 \
		-stdlib=libc++ \
		-mmacosx-version-min=10.7 \
		-Wall \
		-W



first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET):  $(OBJECTS)  
	@test -d cube.app/Contents/MacOS/ || mkdir -p cube.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ParticleSystem.pro ../../../../Qt/5.5/clang_64/mkspecs/macx-clang/qmake.conf ../../../../Qt/5.5/clang_64/mkspecs/features/spec_pre.prf \
		../../../../Qt/5.5/clang_64/mkspecs/qdevice.pri \
		../../../../Qt/5.5/clang_64/mkspecs/features/device_config.prf \
		../../../../Qt/5.5/clang_64/mkspecs/common/unix.conf \
		../../../../Qt/5.5/clang_64/mkspecs/common/mac.conf \
		../../../../Qt/5.5/clang_64/mkspecs/common/macx.conf \
		../../../../Qt/5.5/clang_64/mkspecs/common/sanitize.conf \
		../../../../Qt/5.5/clang_64/mkspecs/common/gcc-base.conf \
		../../../../Qt/5.5/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../../Qt/5.5/clang_64/mkspecs/common/clang.conf \
		../../../../Qt/5.5/clang_64/mkspecs/common/clang-mac.conf \
		../../../../Qt/5.5/clang_64/mkspecs/qconfig.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcollision.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcollision_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquickrenderer.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquickrenderer_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3drenderer.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3drenderer_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_enginio.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../../Qt/5.5/clang_64/mkspecs/features/qt_functions.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/qt_config.prf \
		../../../../Qt/5.5/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../../Qt/5.5/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../../Qt/5.5/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/default_pre.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/resolve_config.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/default_post.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/c++11.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/mac/sdk.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/mac/default_post.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/warn_on.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/qt.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/resources.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/moc.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/unix/opengl.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/unix/thread.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/mac/rez.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/testcase_targets.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/exceptions.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/yacc.prf \
		../../../../Qt/5.5/clang_64/mkspecs/features/lex.prf \
		ParticleSystem.pro \
		/Users/Alice/Qt/5.5/clang_64/lib/QtGui.framework/QtGui.prl \
		/Users/Alice/Qt/5.5/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 -o Makefile ParticleSystem.pro
../../../../Qt/5.5/clang_64/mkspecs/features/spec_pre.prf:
../../../../Qt/5.5/clang_64/mkspecs/qdevice.pri:
../../../../Qt/5.5/clang_64/mkspecs/features/device_config.prf:
../../../../Qt/5.5/clang_64/mkspecs/common/unix.conf:
../../../../Qt/5.5/clang_64/mkspecs/common/mac.conf:
../../../../Qt/5.5/clang_64/mkspecs/common/macx.conf:
../../../../Qt/5.5/clang_64/mkspecs/common/sanitize.conf:
../../../../Qt/5.5/clang_64/mkspecs/common/gcc-base.conf:
../../../../Qt/5.5/clang_64/mkspecs/common/gcc-base-mac.conf:
../../../../Qt/5.5/clang_64/mkspecs/common/clang.conf:
../../../../Qt/5.5/clang_64/mkspecs/common/clang-mac.conf:
../../../../Qt/5.5/clang_64/mkspecs/qconfig.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcollision.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcollision_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquickrenderer.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquickrenderer_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3drenderer.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3drenderer_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_core.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_declarative.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_declarative_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_enginio.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_enginio_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_help.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_location.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_location_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_network.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_script.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_script_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webengine.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkit.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkit_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../../Qt/5.5/clang_64/mkspecs/features/qt_functions.prf:
../../../../Qt/5.5/clang_64/mkspecs/features/qt_config.prf:
../../../../Qt/5.5/clang_64/mkspecs/macx-clang/qmake.conf:
../../../../Qt/5.5/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../../../../Qt/5.5/clang_64/mkspecs/features/exclusive_builds.prf:
../../../../Qt/5.5/clang_64/mkspecs/features/default_pre.prf:
../../../../Qt/5.5/clang_64/mkspecs/features/mac/default_pre.prf:
../../../../Qt/5.5/clang_64/mkspecs/features/resolve_config.prf:
../../../../Qt/5.5/clang_64/mkspecs/features/default_post.prf:
../../../../Qt/5.5/clang_64/mkspecs/features/c++11.prf:
../../../../Qt/5.5/clang_64/mkspecs/features/mac/sdk.prf:
../../../../Qt/5.5/clang_64/mkspecs/features/mac/default_post.prf:
../../../../Qt/5.5/clang_64/mkspecs/features/mac/objective_c.prf:
../../../../Qt/5.5/clang_64/mkspecs/features/warn_on.prf:
../../../../Qt/5.5/clang_64/mkspecs/features/qt.prf:
../../../../Qt/5.5/clang_64/mkspecs/features/resources.prf:
../../../../Qt/5.5/clang_64/mkspecs/features/moc.prf:
../../../../Qt/5.5/clang_64/mkspecs/features/unix/opengl.prf:
../../../../Qt/5.5/clang_64/mkspecs/features/unix/thread.prf:
../../../../Qt/5.5/clang_64/mkspecs/features/mac/rez.prf:
../../../../Qt/5.5/clang_64/mkspecs/features/testcase_targets.prf:
../../../../Qt/5.5/clang_64/mkspecs/features/exceptions.prf:
../../../../Qt/5.5/clang_64/mkspecs/features/yacc.prf:
../../../../Qt/5.5/clang_64/mkspecs/features/lex.prf:
ParticleSystem.pro:
/Users/Alice/Qt/5.5/clang_64/lib/QtGui.framework/QtGui.prl:
/Users/Alice/Qt/5.5/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 -o Makefile ParticleSystem.pro

qmake_all: FORCE

cube.app/Contents/PkgInfo: 
	@test -d cube.app/Contents || mkdir -p cube.app/Contents
	@$(DEL_FILE) cube.app/Contents/PkgInfo
	@echo "APPL????" > cube.app/Contents/PkgInfo
cube.app/Contents/Resources/empty.lproj: 
	@test -d cube.app/Contents/Resources || mkdir -p cube.app/Contents/Resources
	@touch cube.app/Contents/Resources/empty.lproj
	
cube.app/Contents/Info.plist: 
	@test -d cube.app/Contents || mkdir -p cube.app/Contents
	@$(DEL_FILE) cube.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@BUNDLEIDENTIFIER@,com.yourcompany.cube,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,cube,g" -e "s,@TYPEINFO@,????,g" ../../../../Qt/5.5/clang_64/mkspecs/macx-clang/Info.plist.app >cube.app/Contents/Info.plist

all: Makefile \
		cube.app/Contents/PkgInfo \
		cube.app/Contents/Resources/empty.lproj \
		cube.app/Contents/Info.plist $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents src/scene.h src/particle.h GLFunctionsLib/include/GLFunctions.h GLFunctionsLib/include/Mat4.h GLFunctionsLib/include/Vec4.h src/particlesystem.h $(DISTDIR)/
	$(COPY_FILE) --parents src/main.cpp src/scene.cpp src/particle.cpp GLFunctionsLib/src/GLFunctions.cpp GLFunctionsLib/src/Mat4.cpp GLFunctionsLib/src/Vec4.cpp src/particlesystem.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r cube.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

obj/main.o: src/main.cpp /usr/local/include/SDL2/SDL.h \
		/usr/local/include/SDL2/SDL_main.h \
		/usr/local/include/SDL2/SDL_stdinc.h \
		/usr/local/include/SDL2/SDL_config.h \
		/usr/local/include/SDL2/SDL_platform.h \
		/usr/include/AvailabilityMacros.h \
		/usr/include/Availability.h \
		/usr/include/AvailabilityInternal.h \
		/usr/include/TargetConditionals.h \
		/usr/local/include/SDL2/begin_code.h \
		/usr/local/include/SDL2/close_code.h \
		/usr/include/sys/types.h \
		/usr/include/sys/appleapiopts.h \
		/usr/include/sys/cdefs.h \
		/usr/include/sys/_symbol_aliasing.h \
		/usr/include/sys/_posix_availability.h \
		/usr/include/machine/types.h \
		/usr/include/i386/types.h \
		/usr/include/i386/_types.h \
		/usr/include/sys/_types/_int8_t.h \
		/usr/include/sys/_types/_int16_t.h \
		/usr/include/sys/_types/_int32_t.h \
		/usr/include/sys/_types/_int64_t.h \
		/usr/include/sys/_types/_intptr_t.h \
		/usr/include/sys/_types/_uintptr_t.h \
		/usr/include/sys/_types.h \
		/usr/include/machine/_types.h \
		/usr/include/sys/_pthread/_pthread_types.h \
		/usr/include/machine/endian.h \
		/usr/include/i386/endian.h \
		/usr/include/sys/_endian.h \
		/usr/include/libkern/_OSByteOrder.h \
		/usr/include/libkern/i386/_OSByteOrder.h \
		/usr/include/sys/_types/_dev_t.h \
		/usr/include/sys/_types/_blkcnt_t.h \
		/usr/include/sys/_types/_blksize_t.h \
		/usr/include/sys/_types/_gid_t.h \
		/usr/include/sys/_types/_in_addr_t.h \
		/usr/include/sys/_types/_in_port_t.h \
		/usr/include/sys/_types/_ino_t.h \
		/usr/include/sys/_types/_ino64_t.h \
		/usr/include/sys/_types/_key_t.h \
		/usr/include/sys/_types/_mode_t.h \
		/usr/include/sys/_types/_nlink_t.h \
		/usr/include/sys/_types/_id_t.h \
		/usr/include/sys/_types/_pid_t.h \
		/usr/include/sys/_types/_off_t.h \
		/usr/include/sys/_types/_uid_t.h \
		/usr/include/sys/_types/_clock_t.h \
		/usr/include/sys/_types/_size_t.h \
		/usr/include/sys/_types/_ssize_t.h \
		/usr/include/sys/_types/_time_t.h \
		/usr/include/sys/_types/_useconds_t.h \
		/usr/include/sys/_types/_suseconds_t.h \
		/usr/include/sys/_types/_rsize_t.h \
		/usr/include/sys/_types/_errno_t.h \
		/usr/include/sys/_types/_fd_def.h \
		/usr/include/sys/_types/_fd_setsize.h \
		/usr/include/sys/_types/_fd_set.h \
		/usr/include/sys/_types/_fd_clr.h \
		/usr/include/sys/_types/_fd_zero.h \
		/usr/include/sys/_types/_fd_isset.h \
		/usr/include/sys/_types/_fd_copy.h \
		/usr/include/sys/_pthread/_pthread_attr_t.h \
		/usr/include/sys/_pthread/_pthread_cond_t.h \
		/usr/include/sys/_pthread/_pthread_condattr_t.h \
		/usr/include/sys/_pthread/_pthread_mutex_t.h \
		/usr/include/sys/_pthread/_pthread_mutexattr_t.h \
		/usr/include/sys/_pthread/_pthread_once_t.h \
		/usr/include/sys/_pthread/_pthread_rwlock_t.h \
		/usr/include/sys/_pthread/_pthread_rwlockattr_t.h \
		/usr/include/sys/_pthread/_pthread_t.h \
		/usr/include/sys/_pthread/_pthread_key_t.h \
		/usr/include/sys/_types/_fsblkcnt_t.h \
		/usr/include/sys/_types/_fsfilcnt_t.h \
		/usr/include/stdio.h \
		/usr/include/_types.h \
		/usr/include/sys/_types/_va_list.h \
		/usr/include/sys/_types/_null.h \
		/usr/include/sys/stdio.h \
		/usr/include/xlocale/_stdio.h \
		/usr/include/secure/_stdio.h \
		/usr/include/secure/_common.h \
		/usr/include/stdlib.h \
		/usr/include/sys/wait.h \
		/usr/include/sys/signal.h \
		/usr/include/machine/signal.h \
		/usr/include/i386/signal.h \
		/usr/include/machine/_mcontext.h \
		/usr/include/i386/_mcontext.h \
		/usr/include/mach/i386/_structs.h \
		/usr/include/sys/_types/_sigaltstack.h \
		/usr/include/sys/_types/_ucontext.h \
		/usr/include/sys/_types/_sigset_t.h \
		/usr/include/sys/resource.h \
		/usr/include/stdint.h \
		/usr/include/_types/_uint8_t.h \
		/usr/include/_types/_uint16_t.h \
		/usr/include/_types/_uint32_t.h \
		/usr/include/_types/_uint64_t.h \
		/usr/include/_types/_intmax_t.h \
		/usr/include/_types/_uintmax_t.h \
		/usr/include/sys/_types/_timeval.h \
		/usr/include/alloca.h \
		/usr/include/sys/_types/_ct_rune_t.h \
		/usr/include/sys/_types/_rune_t.h \
		/usr/include/sys/_types/_wchar_t.h \
		/usr/include/_xlocale.h \
		/usr/include/xlocale/_stdlib.h \
		/usr/include/stddef.h \
		/usr/include/sys/_types/_offsetof.h \
		/usr/include/sys/_types/_ptrdiff_t.h \
		/usr/include/sys/_types/_wint_t.h \
		/usr/include/memory.h \
		/usr/include/string.h \
		/usr/include/strings.h \
		/usr/include/xlocale/_string.h \
		/usr/include/secure/_string.h \
		/usr/include/inttypes.h \
		/usr/include/xlocale/_inttypes.h \
		/usr/include/ctype.h \
		/usr/include/runetype.h \
		/usr/include/xlocale/_ctype.h \
		/usr/include/math.h \
		/usr/include/iconv.h \
		/usr/local/include/SDL2/SDL_assert.h \
		/usr/include/signal.h \
		/usr/local/include/SDL2/SDL_atomic.h \
		/usr/local/include/SDL2/SDL_audio.h \
		/usr/local/include/SDL2/SDL_error.h \
		/usr/local/include/SDL2/SDL_endian.h \
		/usr/local/include/SDL2/SDL_mutex.h \
		/usr/local/include/SDL2/SDL_thread.h \
		/usr/local/include/SDL2/SDL_rwops.h \
		/usr/local/include/SDL2/SDL_clipboard.h \
		/usr/local/include/SDL2/SDL_cpuinfo.h \
		/usr/local/include/SDL2/SDL_events.h \
		/usr/local/include/SDL2/SDL_video.h \
		/usr/local/include/SDL2/SDL_pixels.h \
		/usr/local/include/SDL2/SDL_rect.h \
		/usr/local/include/SDL2/SDL_surface.h \
		/usr/local/include/SDL2/SDL_blendmode.h \
		/usr/local/include/SDL2/SDL_keyboard.h \
		/usr/local/include/SDL2/SDL_keycode.h \
		/usr/local/include/SDL2/SDL_scancode.h \
		/usr/local/include/SDL2/SDL_mouse.h \
		/usr/local/include/SDL2/SDL_joystick.h \
		/usr/local/include/SDL2/SDL_gamecontroller.h \
		/usr/local/include/SDL2/SDL_quit.h \
		/usr/local/include/SDL2/SDL_gesture.h \
		/usr/local/include/SDL2/SDL_touch.h \
		/usr/local/include/SDL2/SDL_filesystem.h \
		/usr/local/include/SDL2/SDL_haptic.h \
		/usr/local/include/SDL2/SDL_hints.h \
		/usr/local/include/SDL2/SDL_loadso.h \
		/usr/local/include/SDL2/SDL_log.h \
		/usr/local/include/SDL2/SDL_messagebox.h \
		/usr/local/include/SDL2/SDL_power.h \
		/usr/local/include/SDL2/SDL_render.h \
		/usr/local/include/SDL2/SDL_system.h \
		/usr/local/include/SDL2/SDL_timer.h \
		/usr/local/include/SDL2/SDL_version.h \
		src/particlesystem.h \
		src/scene.h \
		GLFunctionsLib/include/Vec4.h \
		src/particle.h \
		GLFunctionsLib/include/GLFunctions.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/main.o src/main.cpp

obj/scene.o: src/scene.cpp src/scene.h \
		/usr/include/stdlib.h \
		/usr/include/Availability.h \
		/usr/include/AvailabilityInternal.h \
		/usr/include/_types.h \
		/usr/include/sys/_types.h \
		/usr/include/sys/cdefs.h \
		/usr/include/sys/_symbol_aliasing.h \
		/usr/include/sys/_posix_availability.h \
		/usr/include/machine/_types.h \
		/usr/include/i386/_types.h \
		/usr/include/sys/_pthread/_pthread_types.h \
		/usr/include/sys/wait.h \
		/usr/include/sys/_types/_pid_t.h \
		/usr/include/sys/_types/_id_t.h \
		/usr/include/sys/signal.h \
		/usr/include/sys/appleapiopts.h \
		/usr/include/machine/signal.h \
		/usr/include/i386/signal.h \
		/usr/include/machine/_mcontext.h \
		/usr/include/i386/_mcontext.h \
		/usr/include/mach/i386/_structs.h \
		/usr/include/sys/_pthread/_pthread_attr_t.h \
		/usr/include/sys/_types/_sigaltstack.h \
		/usr/include/sys/_types/_ucontext.h \
		/usr/include/sys/_types/_sigset_t.h \
		/usr/include/sys/_types/_size_t.h \
		/usr/include/sys/_types/_uid_t.h \
		/usr/include/sys/resource.h \
		/usr/include/stdint.h \
		/usr/include/sys/_types/_int8_t.h \
		/usr/include/sys/_types/_int16_t.h \
		/usr/include/sys/_types/_int32_t.h \
		/usr/include/sys/_types/_int64_t.h \
		/usr/include/_types/_uint8_t.h \
		/usr/include/_types/_uint16_t.h \
		/usr/include/_types/_uint32_t.h \
		/usr/include/_types/_uint64_t.h \
		/usr/include/sys/_types/_intptr_t.h \
		/usr/include/sys/_types/_uintptr_t.h \
		/usr/include/_types/_intmax_t.h \
		/usr/include/_types/_uintmax_t.h \
		/usr/include/sys/_types/_timeval.h \
		/usr/include/machine/endian.h \
		/usr/include/i386/endian.h \
		/usr/include/sys/_endian.h \
		/usr/include/libkern/_OSByteOrder.h \
		/usr/include/libkern/i386/_OSByteOrder.h \
		/usr/include/alloca.h \
		/usr/include/sys/_types/_ct_rune_t.h \
		/usr/include/sys/_types/_rune_t.h \
		/usr/include/sys/_types/_wchar_t.h \
		/usr/include/sys/_types/_null.h \
		/usr/include/_xlocale.h \
		/usr/include/machine/types.h \
		/usr/include/i386/types.h \
		/usr/include/sys/_types/_dev_t.h \
		/usr/include/sys/_types/_mode_t.h \
		/usr/include/xlocale/_stdlib.h \
		GLFunctionsLib/include/Vec4.h \
		src/particle.h \
		/usr/local/include/SDL2/SDL.h \
		/usr/local/include/SDL2/SDL_main.h \
		/usr/local/include/SDL2/SDL_stdinc.h \
		/usr/local/include/SDL2/SDL_config.h \
		/usr/local/include/SDL2/SDL_platform.h \
		/usr/include/AvailabilityMacros.h \
		/usr/include/TargetConditionals.h \
		/usr/local/include/SDL2/begin_code.h \
		/usr/local/include/SDL2/close_code.h \
		/usr/include/sys/types.h \
		/usr/include/sys/_types/_blkcnt_t.h \
		/usr/include/sys/_types/_blksize_t.h \
		/usr/include/sys/_types/_gid_t.h \
		/usr/include/sys/_types/_in_addr_t.h \
		/usr/include/sys/_types/_in_port_t.h \
		/usr/include/sys/_types/_ino_t.h \
		/usr/include/sys/_types/_ino64_t.h \
		/usr/include/sys/_types/_key_t.h \
		/usr/include/sys/_types/_nlink_t.h \
		/usr/include/sys/_types/_off_t.h \
		/usr/include/sys/_types/_clock_t.h \
		/usr/include/sys/_types/_ssize_t.h \
		/usr/include/sys/_types/_time_t.h \
		/usr/include/sys/_types/_useconds_t.h \
		/usr/include/sys/_types/_suseconds_t.h \
		/usr/include/sys/_types/_rsize_t.h \
		/usr/include/sys/_types/_errno_t.h \
		/usr/include/sys/_types/_fd_def.h \
		/usr/include/sys/_types/_fd_setsize.h \
		/usr/include/sys/_types/_fd_set.h \
		/usr/include/sys/_types/_fd_clr.h \
		/usr/include/sys/_types/_fd_zero.h \
		/usr/include/sys/_types/_fd_isset.h \
		/usr/include/sys/_types/_fd_copy.h \
		/usr/include/sys/_pthread/_pthread_cond_t.h \
		/usr/include/sys/_pthread/_pthread_condattr_t.h \
		/usr/include/sys/_pthread/_pthread_mutex_t.h \
		/usr/include/sys/_pthread/_pthread_mutexattr_t.h \
		/usr/include/sys/_pthread/_pthread_once_t.h \
		/usr/include/sys/_pthread/_pthread_rwlock_t.h \
		/usr/include/sys/_pthread/_pthread_rwlockattr_t.h \
		/usr/include/sys/_pthread/_pthread_t.h \
		/usr/include/sys/_pthread/_pthread_key_t.h \
		/usr/include/sys/_types/_fsblkcnt_t.h \
		/usr/include/sys/_types/_fsfilcnt_t.h \
		/usr/include/stdio.h \
		/usr/include/sys/_types/_va_list.h \
		/usr/include/sys/stdio.h \
		/usr/include/xlocale/_stdio.h \
		/usr/include/secure/_stdio.h \
		/usr/include/secure/_common.h \
		/usr/include/stddef.h \
		/usr/include/sys/_types/_offsetof.h \
		/usr/include/sys/_types/_ptrdiff_t.h \
		/usr/include/sys/_types/_wint_t.h \
		/usr/include/memory.h \
		/usr/include/string.h \
		/usr/include/strings.h \
		/usr/include/xlocale/_string.h \
		/usr/include/secure/_string.h \
		/usr/include/inttypes.h \
		/usr/include/xlocale/_inttypes.h \
		/usr/include/ctype.h \
		/usr/include/runetype.h \
		/usr/include/xlocale/_ctype.h \
		/usr/include/math.h \
		/usr/include/iconv.h \
		/usr/local/include/SDL2/SDL_assert.h \
		/usr/include/signal.h \
		/usr/local/include/SDL2/SDL_atomic.h \
		/usr/local/include/SDL2/SDL_audio.h \
		/usr/local/include/SDL2/SDL_error.h \
		/usr/local/include/SDL2/SDL_endian.h \
		/usr/local/include/SDL2/SDL_mutex.h \
		/usr/local/include/SDL2/SDL_thread.h \
		/usr/local/include/SDL2/SDL_rwops.h \
		/usr/local/include/SDL2/SDL_clipboard.h \
		/usr/local/include/SDL2/SDL_cpuinfo.h \
		/usr/local/include/SDL2/SDL_events.h \
		/usr/local/include/SDL2/SDL_video.h \
		/usr/local/include/SDL2/SDL_pixels.h \
		/usr/local/include/SDL2/SDL_rect.h \
		/usr/local/include/SDL2/SDL_surface.h \
		/usr/local/include/SDL2/SDL_blendmode.h \
		/usr/local/include/SDL2/SDL_keyboard.h \
		/usr/local/include/SDL2/SDL_keycode.h \
		/usr/local/include/SDL2/SDL_scancode.h \
		/usr/local/include/SDL2/SDL_mouse.h \
		/usr/local/include/SDL2/SDL_joystick.h \
		/usr/local/include/SDL2/SDL_gamecontroller.h \
		/usr/local/include/SDL2/SDL_quit.h \
		/usr/local/include/SDL2/SDL_gesture.h \
		/usr/local/include/SDL2/SDL_touch.h \
		/usr/local/include/SDL2/SDL_filesystem.h \
		/usr/local/include/SDL2/SDL_haptic.h \
		/usr/local/include/SDL2/SDL_hints.h \
		/usr/local/include/SDL2/SDL_loadso.h \
		/usr/local/include/SDL2/SDL_log.h \
		/usr/local/include/SDL2/SDL_messagebox.h \
		/usr/local/include/SDL2/SDL_power.h \
		/usr/local/include/SDL2/SDL_render.h \
		/usr/local/include/SDL2/SDL_system.h \
		/usr/local/include/SDL2/SDL_timer.h \
		/usr/local/include/SDL2/SDL_version.h \
		GLFunctionsLib/include/GLFunctions.h \
		/usr/include/sys/time.h \
		/usr/include/sys/_types/_timespec.h \
		/usr/include/sys/_types/_timeval64.h \
		/usr/include/time.h \
		/usr/include/machine/_limits.h \
		/usr/include/i386/_limits.h \
		/usr/include/xlocale/_time.h \
		/usr/include/sys/_select.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/scene.o src/scene.cpp

obj/particle.o: src/particle.cpp src/particle.h \
		/usr/local/include/SDL2/SDL.h \
		/usr/local/include/SDL2/SDL_main.h \
		/usr/local/include/SDL2/SDL_stdinc.h \
		/usr/local/include/SDL2/SDL_config.h \
		/usr/local/include/SDL2/SDL_platform.h \
		/usr/include/AvailabilityMacros.h \
		/usr/include/Availability.h \
		/usr/include/AvailabilityInternal.h \
		/usr/include/TargetConditionals.h \
		/usr/local/include/SDL2/begin_code.h \
		/usr/local/include/SDL2/close_code.h \
		/usr/include/sys/types.h \
		/usr/include/sys/appleapiopts.h \
		/usr/include/sys/cdefs.h \
		/usr/include/sys/_symbol_aliasing.h \
		/usr/include/sys/_posix_availability.h \
		/usr/include/machine/types.h \
		/usr/include/i386/types.h \
		/usr/include/i386/_types.h \
		/usr/include/sys/_types/_int8_t.h \
		/usr/include/sys/_types/_int16_t.h \
		/usr/include/sys/_types/_int32_t.h \
		/usr/include/sys/_types/_int64_t.h \
		/usr/include/sys/_types/_intptr_t.h \
		/usr/include/sys/_types/_uintptr_t.h \
		/usr/include/sys/_types.h \
		/usr/include/machine/_types.h \
		/usr/include/sys/_pthread/_pthread_types.h \
		/usr/include/machine/endian.h \
		/usr/include/i386/endian.h \
		/usr/include/sys/_endian.h \
		/usr/include/libkern/_OSByteOrder.h \
		/usr/include/libkern/i386/_OSByteOrder.h \
		/usr/include/sys/_types/_dev_t.h \
		/usr/include/sys/_types/_blkcnt_t.h \
		/usr/include/sys/_types/_blksize_t.h \
		/usr/include/sys/_types/_gid_t.h \
		/usr/include/sys/_types/_in_addr_t.h \
		/usr/include/sys/_types/_in_port_t.h \
		/usr/include/sys/_types/_ino_t.h \
		/usr/include/sys/_types/_ino64_t.h \
		/usr/include/sys/_types/_key_t.h \
		/usr/include/sys/_types/_mode_t.h \
		/usr/include/sys/_types/_nlink_t.h \
		/usr/include/sys/_types/_id_t.h \
		/usr/include/sys/_types/_pid_t.h \
		/usr/include/sys/_types/_off_t.h \
		/usr/include/sys/_types/_uid_t.h \
		/usr/include/sys/_types/_clock_t.h \
		/usr/include/sys/_types/_size_t.h \
		/usr/include/sys/_types/_ssize_t.h \
		/usr/include/sys/_types/_time_t.h \
		/usr/include/sys/_types/_useconds_t.h \
		/usr/include/sys/_types/_suseconds_t.h \
		/usr/include/sys/_types/_rsize_t.h \
		/usr/include/sys/_types/_errno_t.h \
		/usr/include/sys/_types/_fd_def.h \
		/usr/include/sys/_types/_fd_setsize.h \
		/usr/include/sys/_types/_fd_set.h \
		/usr/include/sys/_types/_fd_clr.h \
		/usr/include/sys/_types/_fd_zero.h \
		/usr/include/sys/_types/_fd_isset.h \
		/usr/include/sys/_types/_fd_copy.h \
		/usr/include/sys/_pthread/_pthread_attr_t.h \
		/usr/include/sys/_pthread/_pthread_cond_t.h \
		/usr/include/sys/_pthread/_pthread_condattr_t.h \
		/usr/include/sys/_pthread/_pthread_mutex_t.h \
		/usr/include/sys/_pthread/_pthread_mutexattr_t.h \
		/usr/include/sys/_pthread/_pthread_once_t.h \
		/usr/include/sys/_pthread/_pthread_rwlock_t.h \
		/usr/include/sys/_pthread/_pthread_rwlockattr_t.h \
		/usr/include/sys/_pthread/_pthread_t.h \
		/usr/include/sys/_pthread/_pthread_key_t.h \
		/usr/include/sys/_types/_fsblkcnt_t.h \
		/usr/include/sys/_types/_fsfilcnt_t.h \
		/usr/include/stdio.h \
		/usr/include/_types.h \
		/usr/include/sys/_types/_va_list.h \
		/usr/include/sys/_types/_null.h \
		/usr/include/sys/stdio.h \
		/usr/include/xlocale/_stdio.h \
		/usr/include/secure/_stdio.h \
		/usr/include/secure/_common.h \
		/usr/include/stdlib.h \
		/usr/include/sys/wait.h \
		/usr/include/sys/signal.h \
		/usr/include/machine/signal.h \
		/usr/include/i386/signal.h \
		/usr/include/machine/_mcontext.h \
		/usr/include/i386/_mcontext.h \
		/usr/include/mach/i386/_structs.h \
		/usr/include/sys/_types/_sigaltstack.h \
		/usr/include/sys/_types/_ucontext.h \
		/usr/include/sys/_types/_sigset_t.h \
		/usr/include/sys/resource.h \
		/usr/include/stdint.h \
		/usr/include/_types/_uint8_t.h \
		/usr/include/_types/_uint16_t.h \
		/usr/include/_types/_uint32_t.h \
		/usr/include/_types/_uint64_t.h \
		/usr/include/_types/_intmax_t.h \
		/usr/include/_types/_uintmax_t.h \
		/usr/include/sys/_types/_timeval.h \
		/usr/include/alloca.h \
		/usr/include/sys/_types/_ct_rune_t.h \
		/usr/include/sys/_types/_rune_t.h \
		/usr/include/sys/_types/_wchar_t.h \
		/usr/include/_xlocale.h \
		/usr/include/xlocale/_stdlib.h \
		/usr/include/stddef.h \
		/usr/include/sys/_types/_offsetof.h \
		/usr/include/sys/_types/_ptrdiff_t.h \
		/usr/include/sys/_types/_wint_t.h \
		/usr/include/memory.h \
		/usr/include/string.h \
		/usr/include/strings.h \
		/usr/include/xlocale/_string.h \
		/usr/include/secure/_string.h \
		/usr/include/inttypes.h \
		/usr/include/xlocale/_inttypes.h \
		/usr/include/ctype.h \
		/usr/include/runetype.h \
		/usr/include/xlocale/_ctype.h \
		/usr/include/math.h \
		/usr/include/iconv.h \
		/usr/local/include/SDL2/SDL_assert.h \
		/usr/include/signal.h \
		/usr/local/include/SDL2/SDL_atomic.h \
		/usr/local/include/SDL2/SDL_audio.h \
		/usr/local/include/SDL2/SDL_error.h \
		/usr/local/include/SDL2/SDL_endian.h \
		/usr/local/include/SDL2/SDL_mutex.h \
		/usr/local/include/SDL2/SDL_thread.h \
		/usr/local/include/SDL2/SDL_rwops.h \
		/usr/local/include/SDL2/SDL_clipboard.h \
		/usr/local/include/SDL2/SDL_cpuinfo.h \
		/usr/local/include/SDL2/SDL_events.h \
		/usr/local/include/SDL2/SDL_video.h \
		/usr/local/include/SDL2/SDL_pixels.h \
		/usr/local/include/SDL2/SDL_rect.h \
		/usr/local/include/SDL2/SDL_surface.h \
		/usr/local/include/SDL2/SDL_blendmode.h \
		/usr/local/include/SDL2/SDL_keyboard.h \
		/usr/local/include/SDL2/SDL_keycode.h \
		/usr/local/include/SDL2/SDL_scancode.h \
		/usr/local/include/SDL2/SDL_mouse.h \
		/usr/local/include/SDL2/SDL_joystick.h \
		/usr/local/include/SDL2/SDL_gamecontroller.h \
		/usr/local/include/SDL2/SDL_quit.h \
		/usr/local/include/SDL2/SDL_gesture.h \
		/usr/local/include/SDL2/SDL_touch.h \
		/usr/local/include/SDL2/SDL_filesystem.h \
		/usr/local/include/SDL2/SDL_haptic.h \
		/usr/local/include/SDL2/SDL_hints.h \
		/usr/local/include/SDL2/SDL_loadso.h \
		/usr/local/include/SDL2/SDL_log.h \
		/usr/local/include/SDL2/SDL_messagebox.h \
		/usr/local/include/SDL2/SDL_power.h \
		/usr/local/include/SDL2/SDL_render.h \
		/usr/local/include/SDL2/SDL_system.h \
		/usr/local/include/SDL2/SDL_timer.h \
		/usr/local/include/SDL2/SDL_version.h \
		src/scene.h \
		GLFunctionsLib/include/Vec4.h \
		GLFunctionsLib/include/GLFunctions.h \
		/usr/include/sys/time.h \
		/usr/include/sys/_types/_timespec.h \
		/usr/include/sys/_types/_timeval64.h \
		/usr/include/time.h \
		/usr/include/machine/_limits.h \
		/usr/include/i386/_limits.h \
		/usr/include/xlocale/_time.h \
		/usr/include/sys/_select.h \
		/Library/Frameworks/SDL2_image.framework/Headers/SDL_image.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/particle.o src/particle.cpp

obj/GLFunctions.o: GLFunctionsLib/src/GLFunctions.cpp GLFunctionsLib/include/GLFunctions.h \
		GLFunctionsLib/include/Vec4.h \
		GLFunctionsLib/include/Mat4.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/GLFunctions.o GLFunctionsLib/src/GLFunctions.cpp

obj/Mat4.o: GLFunctionsLib/src/Mat4.cpp GLFunctionsLib/include/Mat4.h \
		GLFunctionsLib/include/Vec4.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Mat4.o GLFunctionsLib/src/Mat4.cpp

obj/Vec4.o: GLFunctionsLib/src/Vec4.cpp GLFunctionsLib/include/Vec4.h \
		GLFunctionsLib/include/Mat4.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Vec4.o GLFunctionsLib/src/Vec4.cpp

obj/particlesystem.o: src/particlesystem.cpp src/particlesystem.h \
		src/scene.h \
		/usr/include/stdlib.h \
		/usr/include/Availability.h \
		/usr/include/AvailabilityInternal.h \
		/usr/include/_types.h \
		/usr/include/sys/_types.h \
		/usr/include/sys/cdefs.h \
		/usr/include/sys/_symbol_aliasing.h \
		/usr/include/sys/_posix_availability.h \
		/usr/include/machine/_types.h \
		/usr/include/i386/_types.h \
		/usr/include/sys/_pthread/_pthread_types.h \
		/usr/include/sys/wait.h \
		/usr/include/sys/_types/_pid_t.h \
		/usr/include/sys/_types/_id_t.h \
		/usr/include/sys/signal.h \
		/usr/include/sys/appleapiopts.h \
		/usr/include/machine/signal.h \
		/usr/include/i386/signal.h \
		/usr/include/machine/_mcontext.h \
		/usr/include/i386/_mcontext.h \
		/usr/include/mach/i386/_structs.h \
		/usr/include/sys/_pthread/_pthread_attr_t.h \
		/usr/include/sys/_types/_sigaltstack.h \
		/usr/include/sys/_types/_ucontext.h \
		/usr/include/sys/_types/_sigset_t.h \
		/usr/include/sys/_types/_size_t.h \
		/usr/include/sys/_types/_uid_t.h \
		/usr/include/sys/resource.h \
		/usr/include/stdint.h \
		/usr/include/sys/_types/_int8_t.h \
		/usr/include/sys/_types/_int16_t.h \
		/usr/include/sys/_types/_int32_t.h \
		/usr/include/sys/_types/_int64_t.h \
		/usr/include/_types/_uint8_t.h \
		/usr/include/_types/_uint16_t.h \
		/usr/include/_types/_uint32_t.h \
		/usr/include/_types/_uint64_t.h \
		/usr/include/sys/_types/_intptr_t.h \
		/usr/include/sys/_types/_uintptr_t.h \
		/usr/include/_types/_intmax_t.h \
		/usr/include/_types/_uintmax_t.h \
		/usr/include/sys/_types/_timeval.h \
		/usr/include/machine/endian.h \
		/usr/include/i386/endian.h \
		/usr/include/sys/_endian.h \
		/usr/include/libkern/_OSByteOrder.h \
		/usr/include/libkern/i386/_OSByteOrder.h \
		/usr/include/alloca.h \
		/usr/include/sys/_types/_ct_rune_t.h \
		/usr/include/sys/_types/_rune_t.h \
		/usr/include/sys/_types/_wchar_t.h \
		/usr/include/sys/_types/_null.h \
		/usr/include/_xlocale.h \
		/usr/include/machine/types.h \
		/usr/include/i386/types.h \
		/usr/include/sys/_types/_dev_t.h \
		/usr/include/sys/_types/_mode_t.h \
		/usr/include/xlocale/_stdlib.h \
		GLFunctionsLib/include/Vec4.h \
		src/particle.h \
		/usr/local/include/SDL2/SDL.h \
		/usr/local/include/SDL2/SDL_main.h \
		/usr/local/include/SDL2/SDL_stdinc.h \
		/usr/local/include/SDL2/SDL_config.h \
		/usr/local/include/SDL2/SDL_platform.h \
		/usr/include/AvailabilityMacros.h \
		/usr/include/TargetConditionals.h \
		/usr/local/include/SDL2/begin_code.h \
		/usr/local/include/SDL2/close_code.h \
		/usr/include/sys/types.h \
		/usr/include/sys/_types/_blkcnt_t.h \
		/usr/include/sys/_types/_blksize_t.h \
		/usr/include/sys/_types/_gid_t.h \
		/usr/include/sys/_types/_in_addr_t.h \
		/usr/include/sys/_types/_in_port_t.h \
		/usr/include/sys/_types/_ino_t.h \
		/usr/include/sys/_types/_ino64_t.h \
		/usr/include/sys/_types/_key_t.h \
		/usr/include/sys/_types/_nlink_t.h \
		/usr/include/sys/_types/_off_t.h \
		/usr/include/sys/_types/_clock_t.h \
		/usr/include/sys/_types/_ssize_t.h \
		/usr/include/sys/_types/_time_t.h \
		/usr/include/sys/_types/_useconds_t.h \
		/usr/include/sys/_types/_suseconds_t.h \
		/usr/include/sys/_types/_rsize_t.h \
		/usr/include/sys/_types/_errno_t.h \
		/usr/include/sys/_types/_fd_def.h \
		/usr/include/sys/_types/_fd_setsize.h \
		/usr/include/sys/_types/_fd_set.h \
		/usr/include/sys/_types/_fd_clr.h \
		/usr/include/sys/_types/_fd_zero.h \
		/usr/include/sys/_types/_fd_isset.h \
		/usr/include/sys/_types/_fd_copy.h \
		/usr/include/sys/_pthread/_pthread_cond_t.h \
		/usr/include/sys/_pthread/_pthread_condattr_t.h \
		/usr/include/sys/_pthread/_pthread_mutex_t.h \
		/usr/include/sys/_pthread/_pthread_mutexattr_t.h \
		/usr/include/sys/_pthread/_pthread_once_t.h \
		/usr/include/sys/_pthread/_pthread_rwlock_t.h \
		/usr/include/sys/_pthread/_pthread_rwlockattr_t.h \
		/usr/include/sys/_pthread/_pthread_t.h \
		/usr/include/sys/_pthread/_pthread_key_t.h \
		/usr/include/sys/_types/_fsblkcnt_t.h \
		/usr/include/sys/_types/_fsfilcnt_t.h \
		/usr/include/stdio.h \
		/usr/include/sys/_types/_va_list.h \
		/usr/include/sys/stdio.h \
		/usr/include/xlocale/_stdio.h \
		/usr/include/secure/_stdio.h \
		/usr/include/secure/_common.h \
		/usr/include/stddef.h \
		/usr/include/sys/_types/_offsetof.h \
		/usr/include/sys/_types/_ptrdiff_t.h \
		/usr/include/sys/_types/_wint_t.h \
		/usr/include/memory.h \
		/usr/include/string.h \
		/usr/include/strings.h \
		/usr/include/xlocale/_string.h \
		/usr/include/secure/_string.h \
		/usr/include/inttypes.h \
		/usr/include/xlocale/_inttypes.h \
		/usr/include/ctype.h \
		/usr/include/runetype.h \
		/usr/include/xlocale/_ctype.h \
		/usr/include/math.h \
		/usr/include/iconv.h \
		/usr/local/include/SDL2/SDL_assert.h \
		/usr/include/signal.h \
		/usr/local/include/SDL2/SDL_atomic.h \
		/usr/local/include/SDL2/SDL_audio.h \
		/usr/local/include/SDL2/SDL_error.h \
		/usr/local/include/SDL2/SDL_endian.h \
		/usr/local/include/SDL2/SDL_mutex.h \
		/usr/local/include/SDL2/SDL_thread.h \
		/usr/local/include/SDL2/SDL_rwops.h \
		/usr/local/include/SDL2/SDL_clipboard.h \
		/usr/local/include/SDL2/SDL_cpuinfo.h \
		/usr/local/include/SDL2/SDL_events.h \
		/usr/local/include/SDL2/SDL_video.h \
		/usr/local/include/SDL2/SDL_pixels.h \
		/usr/local/include/SDL2/SDL_rect.h \
		/usr/local/include/SDL2/SDL_surface.h \
		/usr/local/include/SDL2/SDL_blendmode.h \
		/usr/local/include/SDL2/SDL_keyboard.h \
		/usr/local/include/SDL2/SDL_keycode.h \
		/usr/local/include/SDL2/SDL_scancode.h \
		/usr/local/include/SDL2/SDL_mouse.h \
		/usr/local/include/SDL2/SDL_joystick.h \
		/usr/local/include/SDL2/SDL_gamecontroller.h \
		/usr/local/include/SDL2/SDL_quit.h \
		/usr/local/include/SDL2/SDL_gesture.h \
		/usr/local/include/SDL2/SDL_touch.h \
		/usr/local/include/SDL2/SDL_filesystem.h \
		/usr/local/include/SDL2/SDL_haptic.h \
		/usr/local/include/SDL2/SDL_hints.h \
		/usr/local/include/SDL2/SDL_loadso.h \
		/usr/local/include/SDL2/SDL_log.h \
		/usr/local/include/SDL2/SDL_messagebox.h \
		/usr/local/include/SDL2/SDL_power.h \
		/usr/local/include/SDL2/SDL_render.h \
		/usr/local/include/SDL2/SDL_system.h \
		/usr/local/include/SDL2/SDL_timer.h \
		/usr/local/include/SDL2/SDL_version.h \
		GLFunctionsLib/include/GLFunctions.h \
		/usr/include/sys/time.h \
		/usr/include/sys/_types/_timespec.h \
		/usr/include/sys/_types/_timeval64.h \
		/usr/include/time.h \
		/usr/include/machine/_limits.h \
		/usr/include/i386/_limits.h \
		/usr/include/xlocale/_time.h \
		/usr/include/sys/_select.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/particlesystem.o src/particlesystem.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

